#!/bin/bash
. .travis/common.sh

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu ${DIST} main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
sudo apt-get update
sudo apt-get install ros-hydro-ros-base

. /opt/ros/*/setup.sh

# workspace
CATKIN_WORKSPACE=$build_dir
mkdir -p $CATKIN_WORKSPACE/src

. $CATKIN_WORKSPACE/devel/setup.sh

