#!/bin/bash
. .travis/common.sh

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
sudo apt-get update
sudo apt-get install ros-hydro-ros-base python-catkin-lint

. /opt/ros/*/setup.sh

# workspace
CATKIN_WORKSPACE=$build_dir
ln -s $root_dir/.. $CATKIN_WORKSPACE/src
cd $CATKIN_WORKSPACE
catkin_init_workspace
. $CATKIN_WORKSPACE/devel/setup.sh

