#!/bin/sh
set -ev

# Directories.
root_dir=`pwd`
build_dir="$root_dir/_travis/build"
install_dir="$root_dir/_travis/install"

# Shortcuts.
git_clone="git clone --quiet --recursive"

# Source ROS setup file
. /opt/ros/*/setup.sh

# Create layout.
rm -rf "$build_dir" "$install_dir"
mkdir -p "$build_dir"
mkdir -p "$install_dir"

# Setup environment variables.
export LD_LIBRARY_PATH="$install_dir/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$install_dir/lib/pkgconfig:$PKG_CONFIG_PATH"

export ROS_PACKAGE_PATH="$root_dir:$ROS_PACKAGE_PATH"

install_dependency()
{
    echo "--> Compiling $1"
    mkdir -p "$build_dir/$1"
    cd "$build_dir"
    $git_clone "git://github.com/$1" "$1"
    cd "$build_dir/$1"
    cmake . -DCMAKE_INSTALL_PREFIX:STRING="$install_dir"
    make install
}

install_ros_stack()
{
    echo "--> Compiling $1"
    mkdir -p "$build_dir/$1"
    cd "$build_dir"
    $git_clone "git://github.com/$1" "$1"
    export ROS_PACKAGE_PATH="$build_dir/$1:$ROS_PACKAGE_PATH"
}

# rosmake and install dynamic_graph_bridge
cd "$root_dir"
export ROS_PACKAGE_PATH="$root_dir:$ROS_PACKAGE_PATH"
rosdep install dynamic_graph_bridge_msgs
rosmake dynamic_graph_bridge_msgs
cd build
cmake .. -DCMAKE_INSTALL_PREFIX:STRING="$install_dir"
rosmake dynamic_graph_bridge_msgs
make install

